{% set name = "documenteer" %}  {# PyPI name #}
{% set version = "0.6.0" %}

package:
  name: "lsst-documenteer"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "3325f06e3a725cb485bec22f8ebe302e4ca721465cac493f3548b9abef96e88b"

build:
  number: 0

outputs:
  - name: documenteer
    script: documenteer-build.sh
    build:
      noarch: python
      entry_points:
        - stack-docs = documenteer.stackdocs.stackcli:main
        - package-docs = documenteer.stackdocs.packagecli:main
        - build-stack-docs = documenteer.stackdocs.build:run_build_cli
        - refresh-lsst-bib = documenteer.bin.refreshlsstbib:run
    requirements:
      host:
        - python >=3.0
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >=3.7
        - sphinx >=2.0
        - click
        - gitpython
        - pyyaml
        - requests
        - sphinxcontrib-bibtex
    test:
      imports:
        - documenteer
        - documenteer.bin
        - documenteer.sphinxconfig
        - documenteer.sphinxext
        - documenteer.sphinxext.lssttasks
        - documenteer.stackdocs
    about:
      home: "https://github.com/lsst-sqre/documenteer"
      license: "MIT"
      license_family: "MIT"
      license_file: "LICENSE"
      summary: "Documenteer provides tools, extensions, and configurations for Vera Rubin Observatory Legacy Survey of Space and Time (LSST) Sphinx documentation projects."
      doc_url: "https://documenteer.lsst.io/"
      dev_url: "https://github.com/lsst-sqre/documenteer"

  - name: lsst-documenteer-technote
    requirements:
      run:
        - {{ pin_subpackage("documenteer", exact=True) }}
        - lsst-dd-rtd-theme >=0.2.3,<0.3.0
        - sphinx-prompt
    test:
      commands:
        - refresh-lsst-bib --help
    about:
      home: "https://github.com/lsst-sqre/documenteer"
      license: "MIT"
      license_family: "MIT"
      license_file: "LICENSE"
      summary: "Meta package for Rubin Observatory LSST technical note projects."
      doc_url: "https://documenteer.lsst.io/"
      dev_url: "https://github.com/lsst-sqre/documenteer"

  - name: lsst-documenteer-pipelines
    requirements:
      run:
        - {{ pin_subpackage("documenteer", exact=True) }}
        - lsst-sphinx-bootstrap-theme >=0.2.0,<0.3.0
        - sphinx-prompt
        - numpydoc
        - sphinx-automodapi
        - sphinx-jinja
        - sphinx-click
        - sphinxcontrib-autoprogram
        - sphinxcontrib-doxylink
    test:
      commands:
         - stack-docs --help
         - package-docs --help
         - build-stack-docs --help
    about:
      home: "https://github.com/lsst-sqre/documenteer"
      license: "MIT"
      license_family: "MIT"
      license_file: "LICENSE"
      summary: "Meta package for Rubin Observatory LSST Science Pipelines documentation."
      doc_url: "https://documenteer.lsst.io/"
      dev_url: "https://github.com/lsst-sqre/documenteer"


extra:
  recipe-maintainers:
    - jonathansick
