{% set name = "documenteer" %}  {# PyPI name #}
{% set version = "2.0.0" %}
{% set python_min = "3.12" %}

package:
  name: lsst-documenteer
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7520bfbca2f7f09a53b8326e1b9ed04fcfdf1715088dc21ecd61b4830eb703d

build:
  number: 0

outputs:
  - name: documenteer
    script: documenteer-build.sh
    build:
      noarch: python
      entry_points:
        - documenteer = documenteer.cli:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }}
        - docutils >=0.20
        - sphinx >=7,<8.2
        - pyyaml
        - gitpython
        - requests
        - click
        - sphinxcontrib-bibtex >=2.6.5
        - pybtex >=0.25.0
        - pydantic >=2.0.0
        - urllib3
        - pylatexenc
        - tomlkit
    test:
      requires:
        - python {{ python_min }}
      imports:
        - documenteer
        - documenteer.cli
        - documenteer.ext.bibtex
        - documenteer.ext.githubbibcache
        - documenteer.ext.jira
        - documenteer.ext.lsstdocushare
        - documenteer.ext.mockcoderefs
        - documenteer.ext.openapi
        - documenteer.ext.redoc
        - documenteer.ext.remotecodeblock
    about:
      home: https://github.com/lsst-sqre/documenteer
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Documenteer provides tools, extensions, and configurations for Vera Rubin Observatory Legacy Survey of Space and Time (LSST) Sphinx documentation projects.
      doc_url: https://documenteer.lsst.io/
      dev_url: https://github.com/lsst-sqre/documenteer

  - name: lsst-documenteer-guide
    requirements:
      run:
        - {{ pin_subpackage("documenteer", exact=True) }}
        - autodoc-pydantic
        - sphinx-design
        - pydata-sphinx-theme >=0.16.1,<0.17.0
        - sphinx-autodoc-typehints
        - sphinx-automodapi
        - sphinx-copybutton
        - sphinx-prompt
        - sphinx-jinja >=2
        - myst-parser
        - myst-nb
        - markdown-it-py
        - linkify-it-py
        - sphinxcontrib-mermaid >=1
        - sphinxext-opengraph
        - sphinxcontrib-jquery
        - sphinxext-rediraffe
        - sphinxcontrib-youtube
        - sphinx-favicon
    test:
      imports:
        - documenteer
    about:
      home: https://github.com/lsst-sqre/documenteer
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Meta package for Rubin Observatory LSST technical note projects.
      doc_url: https://documenteer.lsst.io/
      dev_url: https://github.com/lsst-sqre/documenteer

  - name: lsst-documenteer-technote
    requirements:
      run:
        - {{ pin_subpackage("documenteer", exact=True) }}
        - technote >=0.9.0,<0.10.0
        - sphinx-prompt
        - sphinxcontrib-mermaid >=1
        - sphinx-diagrams
        - sphinx-design
        - myst-nb
        - sphinxcontrib-youtube
    test:
      import:
        - documenteer
    about:
      home: https://github.com/lsst-sqre/documenteer
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Meta package for Rubin Observatory LSST technical note projects.
      doc_url: https://documenteer.lsst.io/
      dev_url: https://github.com/lsst-sqre/documenteer

about:
  home: https://github.com/lsst-sqre/documenteer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Documenteer provides tools, extensions, and configurations for Vera Rubin Observatory Legacy Survey of Space and Time (LSST) Sphinx documentation projects.
  doc_url: https://documenteer.lsst.io/
  dev_url: https://github.com/lsst-sqre/documenteer

extra:
  recipe-maintainers:
    - jonathansick
