{% set name = "documenteer" %}  {# PyPI name #}
{% set version = "1.4.3" %}
{% set python_min = "3.11" %}

package:
  name: lsst-documenteer
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b0cb1a5b9982ff8fce7121d479547e754a68bd7628620633653d2a5eeb883b5

build:
  number: 0

outputs:
  - name: documenteer
    build:
      script: $PYTHON -m pip install --no-deps --no-build-isolation --ignore-installed -vv .
      noarch: python
      entry_points:
        - documenteer = documenteer.cli:main
        - stack-docs = documenteer.stackdocs.stackcli:main
        - package-docs = documenteer.stackdocs.packagecli:main
    requirements:
      build:
        - python {{ python_min }} # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }}
        - sphinx =8.1
        - click
        - gitpython
        - pyyaml
        - requests
        - sphinxcontrib-bibtex >=2
        - importlib-metadata
        - tomlkit
        - pydantic >=2
        - git
        - docutils =0.20
        - pylatexenc
        - urllib3
    test:
      imports:
        - documenteer
        - documenteer.conf
        - documenteer.ext
        - documenteer.ext.lssttasks
        - documenteer.stackdocs
      source_files:
        - tests/
        - demo/
      requires:
        - python {{ python_min }}
        - pytest
        - pytest-mock
        - lxml
        - cssselect
        - coverage
        - sphinx-jinja >=2
      commands:
        - pytest
    about:
      home: https://github.com/lsst-sqre/documenteer
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Documenteer provides tools, extensions, and configurations for Vera Rubin Observatory Legacy Survey of Space and Time (LSST) Sphinx documentation projects.
      doc_url: https://documenteer.lsst.io/
      dev_url: https://github.com/lsst-sqre/documenteer

  - name: lsst-documenteer-guide
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage("documenteer", exact=True) }}
        - autodoc-pydantic
        - sphinx-prompt
        - pydata-sphinx-theme >=0.10.0,<0.13.0
        - sphinx-autodoc-typehints <1.23.0
        - sphinx-automodapi
        - sphinx-copybutton
        - myst-parser
        - markdown-it-py
        - linkify-it-py
        - mdit-py-plugins
        - sphinxcontrib-mermaid
        - sphinxext-opengraph
        - sphinx-design
        - sphinxcontrib-redoc
        - sphinxcontrib-jquery
        - sphinxcontrib-youtube
        - sphinxext-rediraffe
        - sphinx-jinja >=2
    test:
      imports:
        - documenteer
    about:
      home: https://github.com/lsst-sqre/documenteer
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Meta package for Rubin Observatory LSST technical note projects.
      doc_url: https://documenteer.lsst.io/
      dev_url: https://github.com/lsst-sqre/documenteer

  - name: lsst-documenteer-technote
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage("documenteer", exact=True) }}
        - technote =0.9
        - sphinx-prompt
        - sphinxcontrib-mermaid
        - sphinx-diagrams
        - sphinx-design
        - myst-nb
        - sphinxcontrib-youtube
    about:
      home: https://github.com/lsst-sqre/documenteer
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Meta package for Rubin Observatory LSST technical note projects.
      doc_url: https://documenteer.lsst.io/
      dev_url: https://github.com/lsst-sqre/documenteer

  - name: lsst-documenteer-pipelines
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage("documenteer", exact=True) }}
        - lsst-sphinx-bootstrap-theme >=0.2.0,<0.3.0
        - numpydoc
        - sphinx-automodapi
        - sphinx-jinja >=2
        - sphinx-prompt
        - sphinx-click
        - sphinxcontrib-doxylink
        - sphinxcontrib-autoprogram
        - graphviz
        - sphinxcontrib-jquery
    test:
      commands:
        - stack-docs --help
        - package-docs --help
    about:
      home: https://github.com/lsst-sqre/documenteer
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Meta package for Rubin Observatory LSST Science Pipelines documentation.
      doc_url: https://documenteer.lsst.io/
      dev_url: https://github.com/lsst-sqre/documenteer

about:
  home: https://github.com/lsst-sqre/documenteer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Documenteer provides tools, extensions, and configurations for Vera Rubin Observatory Legacy Survey of Space and Time (LSST) Sphinx documentation projects.
  doc_url: https://documenteer.lsst.io/
  dev_url: https://github.com/lsst-sqre/documenteer

extra:
  recipe-maintainers:
    - jonathansick
